defence/urls.py
from django.urls import path, include
from defence import views

urlpatterns = [
    path('', views.post_list,name='post_list'),
    path('latest', views.latest_news,name='latest'),
    path('asia', views.asian_country_post,name='asian_country_post'),
    path('europe', views.europe_country_post,name='europe_country_post'),
    path('aboutus', views.about_us,name='aboutus'),
    path('contact_us', views.contact_us,name='contact_us'),
    path('contact', views.contact_form,name='contact'),
    path('broadcast', views.broadcast_video,name='broadcast'),
    path('post_detail/<int:pk>',  views.post_detail,name='post_detail'),
    path('like', views.like_post,name='like_post'),
    
]

app_name = 'defence'

defence_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('defence.urls', namespace='defence')),
    path('accounts/', include('allauth.urls',)),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/aboutus.html
<!DOCTYPE HTML>
{% extends 'base.html'%}

{% load static%}
{% block container_block %}

<html>
<head>
<style>
.center {
  text-align: center;
  color: red;
}
</style>
</head>
<body>
<br>
<h1 class="center">About Us</h1>
<br> 
  
<!-- technology-left -->
	<div class="technology">
	<div class="container">
		<div class="col-md-9 technology-left">
		<div class="tech-no">
			<!-- technology-top -->
			
			  <div class="tc-ch wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
				
					<div class="tch-img">
                    <img src={{ company_detail.image.url }} class="img-responsive" alt="" width="750px" height="420px">
						
					</div>
					
						<p>{{company_detail.details}}</p>
						
						
						<div class="soci">
							<ul>
								<li class="hvr-rectangle-out"><a class="fb" href="#"></a></li>
								<li class="hvr-rectangle-out"><a class="twit" href="#"></a></li>
								<li class="hvr-rectangle-out"><a class="goog" href="#"></a></li>
								<li class="hvr-rectangle-out"><a class="pin" href="#"></a></li>
								<li class="hvr-rectangle-out"><a class="drib" href="#"></a></li>
							</ul>
						</div>
						<div class="clearfix"></div>
			</div> 
			<div class="clearfix"></div>
			
            
			
			</div>
		</div>
		<!-- technology-right -->
		<div class="col-md-3 technology-right">
				
				
				<div class="blo-top1">
							
					<div class="tech-btm">
					{% comment %} <div class="search-1 wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
							<form action="#" method="post">
								<input type="search" name="Search" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}" required="">
								<input type="submit" value=" ">
							</form>
						</div> {% endcomment %}
					<h4>Popular Posts </h4>
                    {% for item in popular_post%}
						<div class="blog-grids wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
							<div class="blog-grid-left">
                            
								<a href="singlepage.html"><img src={{ item.image.url }} class="img-responsive" alt="" width="100px" height="76px"></a>
							</div>
							<div class="blog-grid-right">
								
								<h5><a href="{% url 'defence:post_detail'  pk=item.id %}">{{item.title|truncatechars:25}}</a> 
                                <br> views: {{item.post_views}} </h5>
							</div>
							<div class="clearfix"> </div>
						</div>
                        {% endfor %}
						
						<div class="insta wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
					
					</div>
					
					
					</div>
					
					
					
				</div>
				
			
		</div>
		<div class="clearfix"></div>
	</div>
</div>

</body>
</html>
{% endblock %}

templates/asia.html
<!DOCTYPE HTML>
{% extends 'base.html'%}

{% load static%}

    <!-- Main Content -->
{% block container_block %}

	<!--start-main-->
	<div class="header-bottom">
		<div class="container">
			<div class="logo wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
				<h1><a href="index.html">Indian Defence Research wing</a></h1>
				<p><label class="of"></label>LET'S MAKE A PERFECT STYLE<label class="on"></label></p>
			</div>
		</div>
	</div>
<!-- banner -->

<div class="banner">
<div class="container">	
		<h2>Contrary to popular belief, Lorem Ipsum simply</h2>
		<!-- <p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
		<a href="singlepage.html">READ MORE</a> -->
	</div>
</div>

	<!-- technology-left -->
	<div class="technology">
	<div class="container">
		<div class="col-md-9 technology-left">
		<div class="tech-no">
			<!-- technology-top -->
			
			  <div class="tc-ch wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
				
					<div class="tch-img">
                    <a href="{% url 'defence:post_detail'  pk=latest_post.id %}">
                    <img class="card-img-top" src={{ latest_post.image.url }} class="img-responsive" alt="" width="750px" height="420px">
						</a>
					</div>
					
					<h3><a href="{% url 'defence:post_detail'  pk=latest_post.id %}">{{latest_post.title}}</a></h3>
					<h6>BY <a href="singlepage.html">{{latest_post.user|upper}} </a>{{latest_post.created}} views:{{latest_post.post_views}}</h6>
						<p>{{latest_post.body|truncatewords_html:100}}</p>
						
						<div class="bht1">
							<a href="{% url 'defence:post_detail'  pk=latest_post.id %}">Continue Reading</a>
						</div>
						<div class="soci">
							<ul>
								<li class="hvr-rectangle-out"><a class="fb" href="#"></a></li>
								<li class="hvr-rectangle-out"><a class="twit" href="#"></a></li>
								<li class="hvr-rectangle-out"><a class="goog" href="#"></a></li>
								<li class="hvr-rectangle-out"><a class="pin" href="#"></a></li>
								<li class="hvr-rectangle-out"><a class="drib" href="#"></a></li>
							</ul>
						</div>
						<div class="clearfix"></div>
			</div> 
			<div class="clearfix"></div>
			
            {% for post in asian_country_post %}
			<div class="wthree">
            
				 <div class="col-md-6 wthree-left wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
                 
					<div class="tch-img">
                    <a href="{% url 'defence:post_detail'  pk=post.id %}">
                    <img  src={{ post.image.url }} class="img-responsive" alt="" width="365px" height="220px">
						</a>
							
						</div>
				 </div>
				 <div class="col-md-6 wthree-right wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
						<h3> <a href="{% url 'defence:post_detail'  pk=post.id %}">{{post.title}}</a></h3>
						<h6>BY <a href="singlepage.html">{{post.user}} </a>{{post.created}} views:{{post.post_views}}</h6>
							<p>{{post.body|truncatewords_html:20}}</p>
							<div class="bht1">
								<a href="{% url 'defence:post_detail'  pk=post.id %}">Read More</a>
							</div>
							<div class="soci">
								<ul>
									
									<li class="hvr-rectangle-out"><a class="twit" href="#"></a></li>
									<li class="hvr-rectangle-out"><a class="pin" href="#"></a></li>
								</ul>
							</div>
							<div class="clearfix"></div>
					
				 </div>
					<div class="clearfix"></div>
                    
			</div>
            {% endfor%}
			
			
			</div>
		</div>
		<!-- technology-right -->
		<div class="col-md-3 technology-right">
				
				
				<div class="blo-top1">
							
					<div class="tech-btm">
					<div class="search-1 wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
							<form action="#" method="post">
								<input type="search" name="Search" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}" required="">
								<input type="submit" value=" ">
							</form>
						</div>
					<h4>Popular Posts </h4>
                    {% for item in popular_post%}
						<div class="blog-grids wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
							<div class="blog-grid-left">
                            
								<a href="singlepage.html"><img src={{ item.image.url }} class="img-responsive" alt="" width="90px" height="56px"></a>
							</div>
							<div class="blog-grid-right">
								
								<h5><a href="{% url 'defence:post_detail'  pk=item.id %}">{{item.title|truncatechars:20}}</a> views: {{item.post_views}} </h5>
							</div>
							<div class="clearfix"> </div>
						</div>
                        {% endfor %}
						
						<div class="insta wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
					
					</div>
					
					
					</div>
					
					
					
				</div>
				
			
		</div>
		<div class="clearfix"></div>
        
		<!-- technology-right -->
	</div>
</div>
{%include 'pagination.html' with page=asian_country_post %} 

{% endblock %}

templates/broadcast.html
<!DOCTYPE HTML>

{% extends 'base.html'%}
{% load embed_video_tags %}
{% load static%}

{% block container_block %}

<html>
<head>
<style>
.center {
  text-align: center;
  color: red;
}
</style>
</head>
<body>
<br>
<h1 class="center">Broadcast Video</h1>
<br> 

<!-- technology-left -->

	<div class="technology">
	<div class="container">
   
		<div class="col-md-9 technology-left">
        {% for item in my_video %}
		<div class="tech-no">
			<!-- technology-top -->
			
			  <div class="tc-ch wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
				
					<div class="tch-img">
                    {% video item.video '750x420' %}
                    {% comment %} <img class="card-img-top" src={{ post_obj.image.url }} class="img-responsive" alt="" width="750px" height="420px"> {% endcomment %}
						
					</div>
					
					<h3>{{item.post.title}}</h3>
					<h6>Published BY :{{item.post.user|upper}}{{post_obj.user|upper}} {{item.post.created}}</h6>
						<p>{{item.post.body}}</p>
						
						
						<div class="soci">
							<ul>
								<li class="hvr-rectangle-out"><a class="fb" href="#"></a></li>
								<li class="hvr-rectangle-out"><a class="twit" href="#"></a></li>
								<li class="hvr-rectangle-out"><a class="goog" href="#"></a></li>
								{% comment %} <li class="hvr-rectangle-out"><a class="pin" href="#"></a></li>
								<li class="hvr-rectangle-out"><a class="drib" href="#"></a></li> {% endcomment %}
							</ul>
						</div>
						<div class="clearfix"></div>
			</div> 
			<div class="clearfix"></div>
			
			</div>
            {% endfor %}
		</div>
        
		<!-- technology-right -->
		<div class="col-md-3 technology-right">
				
				<div class="blo-top1">
							
					<div class="tech-btm">
					<div class="search-1 wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
							<form action="#" method="post">
								<input type="search" name="Search" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}" required="">
								<input type="submit" value=" ">
							</form>
						</div>
					<h4>Popular Posts </h4>
                    {% for item in popular_post%}
						<div class="blog-grids wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
							<div class="blog-grid-left">
                            
								<a href="singlepage.html"><img src={{ item.image.url }} class="img-responsive" alt="" width="100px" height="76px"></a>
							</div>
							<div class="blog-grid-right">
								
								<h5><a href="{% url 'defence:post_detail'  pk=item.id %}">{{item.title|truncatechars:25}}</a> 
                                <br> views: {{item.post_views}} </h5>
							</div>
							<div class="clearfix"> </div>
						</div>
                        {% endfor %}
						
						<div class="insta wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
					
					</div>
					</div>
					
				</div>
		</div>
		<div class="clearfix"></div>
	</div>
</div>

</body>
</html>
{% endblock %}

templates/europe.html
<!DOCTYPE HTML>
{% extends 'base.html'%}

{% load static%}

    <!-- Main Content -->
{% block container_block %}

	<!--start-main-->
	<div class="header-bottom">
		<div class="container">
			<div class="logo wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
				<h1><a href="index.html">Indian Defence Research wing</a></h1>
				<p><label class="of"></label>LET'S MAKE A PERFECT STYLE<label class="on"></label></p>
			</div>
		</div>
	</div>
<!-- banner -->

<div class="banner">
<div class="container">	
		<h2>Contrary to popular belief, Lorem Ipsum simply</h2>
		<!-- <p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
		<a href="singlepage.html">READ MORE</a> -->
	</div>
</div>

	<!-- technology-left -->
	<div class="technology">
	<div class="container">
		<div class="col-md-9 technology-left">
		<div class="tech-no">
			<!-- technology-top -->
			
			  <div class="tc-ch wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
				
					<div class="tch-img">
                    <a href="{% url 'defence:post_detail'  pk=latest_post.id %}">
                    <img class="card-img-top" src={{ latest_post.image.url }} class="img-responsive" alt="" width="750px" height="420px">
						</a>
					</div>
					
					<h3><a href="{% url 'defence:post_detail'  pk=latest_post.id %}">{{latest_post.title}}</a></h3>
					<h6>BY <a href="singlepage.html">{{latest_post.user|upper}} </a>{{latest_post.created}} views:{{latest_post.post_views}}</h6>
						<p>{{latest_post.body|truncatewords_html:100}}</p>
						
						<div class="bht1">
							<a href="{% url 'defence:post_detail'  pk=latest_post.id %}">Continue Reading</a>
						</div>
						<div class="soci">
							<ul>
								<li class="hvr-rectangle-out"><a class="fb" href="#"></a></li>
								<li class="hvr-rectangle-out"><a class="twit" href="#"></a></li>
								<li class="hvr-rectangle-out"><a class="goog" href="#"></a></li>
								{% comment %} <li class="hvr-rectangle-out"><a class="pin" href="#"></a></li>
								<li class="hvr-rectangle-out"><a class="drib" href="#"></a></li> {% endcomment %}
							</ul>
						</div>
						<div class="clearfix"></div>
			</div> 
			<div class="clearfix"></div>
			
            {% for post in europe_country_post %}
			<div class="wthree">
            
				 <div class="col-md-6 wthree-left wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
                 
					<div class="tch-img">
                    <a href="{% url 'defence:post_detail'  pk=post.id %}">
                    <img  src={{ post.image.url }} class="img-responsive" alt="" width="365px" height="220px">
						</a>
							
						</div>
				 </div>
				 <div class="col-md-6 wthree-right wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
						<h3> <a href="{% url 'defence:post_detail'  pk=post.id %}">{{post.title}}</a></h3>
						<h6>BY <a href="singlepage.html">{{post.user}} </a>{{post.created}} views:{{post.post_views}}</h6>
							<p>{{post.body|truncatewords_html:20}}</p>
							<div class="bht1">
								<a href="{% url 'defence:post_detail'  pk=post.id %}">Read More</a>
							</div>
							<div class="soci">
								<ul>
									
									<li class="hvr-rectangle-out"><a class="twit" href="#"></a></li>
									<li class="hvr-rectangle-out"><a class="pin" href="#"></a></li>
								</ul>
							</div>
							<div class="clearfix"></div>
					
				 </div>
					<div class="clearfix"></div>
                    
			</div>
            {% endfor%}
			
			
			</div>
		</div>
		<!-- technology-right -->
		<div class="col-md-3 technology-right">
				
				
				<div class="blo-top1">
							
					<div class="tech-btm">
					<div class="search-1 wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
							<form action="#" method="post">
								<input type="search" name="Search" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}" required="">
								<input type="submit" value=" ">
							</form>
						</div>
					<h4>Popular Posts </h4>
                    {% for item in popular_post%}
						<div class="blog-grids wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
							<div class="blog-grid-left">
                            
								<a href="singlepage.html"><img src={{ item.image.url }} class="img-responsive" alt="" width="90px" height="56px"></a>
							</div>
							<div class="blog-grid-right">
								
								<h5><a href="{% url 'defence:post_detail'  pk=item.id %}">{{item.title|truncatechars:20}}</a> views: {{item.post_views}} </h5>
							</div>
							<div class="clearfix"> </div>
						</div>
                        {% endfor %}
						
						<div class="insta wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
					
					</div>
					
					
					</div>
					
					
					
				</div>
				
			
		</div>
		<div class="clearfix"></div>
        
		<!-- technology-right -->
	</div>
</div>
{%include 'pagination.html' with page=europe_country_post %} 

{% endblock %}

templates/latest_news.html
<!DOCTYPE HTML>
{% extends 'base.html'%}

{% load static%}

    <!-- Main Content -->
{% block container_block %}

	<!--start-main-->
	<div class="header-bottom">
		<div class="container">
			<div class="logo wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
				<h1><a href="index.html">Latest News</a></h1>
				<p><label class="of"></label>LET'S MAKE A PERFECT STYLE<label class="on"></label></p>
			</div>
		</div>
	</div>
<!-- banner -->

<div class="banner">
<div class="container">	
		<h2>Contrary to popular belief, Lorem Ipsum simply</h2>
		<!-- <p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
		<a href="singlepage.html">READ MORE</a> -->
	</div>
</div>

	<!-- technology-left -->
	<div class="technology">
	<div class="container">
    
		<div class="col-md-9 technology-left">
        {% for latest_post in latest_post%}
		<div class="tech-no">
			<!-- technology-top -->
			
			  <div class="tc-ch wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
				
					<div class="tch-img">
                    <a href="{% url 'defence:post_detail'  pk=latest_post.id %}">
                    <img class="card-img-top" src={{ latest_post.image.url }} class="img-responsive" alt="" width="750px" height="420px">
						</a>
					</div>
					
					<h3><a href="{% url 'defence:post_detail'  pk=latest_post.id %}">{{latest_post.title}}</a></h3>
					<h6>BY <a href="singlepage.html">{{latest_post.user|upper}} </a>{{latest_post.created}} views:{{latest_post.post_views}}</h6>
						<p>{{latest_post.body|truncatewords_html:100}}</p>
						
						<div class="bht1">
							<a href="{% url 'defence:post_detail'  pk=latest_post.id %}">Continue Reading</a>
						</div>
						<div class="soci">
							<ul>
								<li class="hvr-rectangle-out"><a class="fb" href="#"></a></li>
								<li class="hvr-rectangle-out"><a class="twit" href="#"></a></li>
								<li class="hvr-rectangle-out"><a class="goog" href="#"></a></li>
								{% comment %} <li class="hvr-rectangle-out"><a class="pin" href="#"></a></li>
								<li class="hvr-rectangle-out"><a class="drib" href="#"></a></li> {% endcomment %}
							</ul>
						</div>
						<div class="clearfix"></div>
                        
			</div> 
            
			<div class="clearfix"></div>
			
			</div>
            {% endfor %}
		</div>
        
		<!-- technology-right -->
		<div class="col-md-3 technology-right">
				
				<div class="blo-top1">
							
					<div class="tech-btm">
					<div class="search-1 wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
							<form action="#" method="post">
								<input type="search" name="Search" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}" required="">
								<input type="submit" value=" ">
							</form>
						</div>
					<h4>Popular Posts </h4>
                    {% for item in popular_post%}
						<div class="blog-grids wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
							<div class="blog-grid-left">
                            
								<a href="singlepage.html"><img src={{ item.image.url }} class="img-responsive" alt="" width="90px" height="56px"></a>
							</div>
							<div class="blog-grid-right">
								
								<h5><a href="{% url 'defence:post_detail'  pk=item.id %}">{{item.title|truncatechars:20}}</a> views: {{item.post_views}} </h5>
							</div>
							<div class="clearfix"> </div>
						</div>
                        {% endfor %}
						
                        <h4>Trending News </h4>
                    {% for item in trends%}
						<div class="blog-grids wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
							<div class="blog-grid-left">
                            
								<a href="singlepage.html"><img src={{ item.image.url }} class="img-responsive" alt="" width="90px" height="56px"></a>
							</div>
							<div class="blog-grid-right">
								
								<h5><a href="{% url 'defence:post_detail'  pk=item.id %}">{{item.title|truncatechars:25}}</a> </h5>
                                Trending at : {{forloop.counter}} 
							</div>
							<div class="clearfix"> </div>
						</div>
                        {% endfor %}      
						<div class="insta wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
					
					</div>
						<div class="insta wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
					
					</div>
					
					
					</div>
					
				</div>
				
		</div>
		<div class="clearfix"></div>
        
		<!-- technology-right -->
	</div>
</div>
{%include 'pagination.html' with page=latest_post %} 

{% endblock %}

templates/post_detail.html
<!DOCTYPE HTML>
{% extends 'base.html'%}
{% load socialaccount %}
{% load static%}

{% block container_block %}
{% providers_media_js %}
<html>
<head>
<style>
.center {
  text-align: center;
  color: red;
}
</style>
</head>
<body>
<br>
<h1 class="center">News in Detail</h1>
<br> 

	<!-- technology-left -->
	<div class="technology">
	<div class="container">
		<div class="col-md-9 technology-left">
		<div class="tech-no">
			<!-- technology-top -->
			
			  <div class="tc-ch wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
				
					<div class="tch-img">
                    
                    <img class="card-img-top" src={{ post_obj.image.url }} class="img-responsive" alt="" width="750px" height="420px">
						
					</div>
					
					<h3>{{post_obj.title}}</h3>
					<h6>Published BY :{{post_obj.user|upper}} {{post_obj.created}} Views {{post_obj.post_views}}</h6>
						<p>{{post_obj.body}}</p>
						
				<!--include like section file-->
				<form action="{% url 'defence:like_post' %}"  method="post">
               {% csrf_token %}
                   {% if is_liked %}

         <button type="submit"  name="post_id" value="{{post_obj.id}}" class="btn btn-danger  " >
         <i class="far fa-thumbs-down fa-2x" ></i></button>
            {% else %}
          <button type="submit"  name="post_id" value="{{post_obj.id}}" class="btn btn-primary " ><i class="far fa-thumbs-up fa-2x"></i></button>
         {% endif %}
              </form>
            <h3>  {{total_likes}} Like{{total_likes|pluralize}}</h3>
           

			{% with comments.count as comments_count %}
            <h2>{{comments_count}} Comment{{comments_count|pluralize}}</h2>
            {% endwith %}
            {% if comments %}
              {% for comment in comments %}
               <p id='ch'><span style = "color:#00bfff;   border-bottom: 3px solid yellow;">
                 Comment {{forloop.counter}}: By {{comment.name}} On {{comment.created}}</span></p>
              <div class="cv">
                {{comment.body|linebreaks}}
              </div>
             {% endfor %}
                 <hr>
            {% else %}
              <p>There Are No Comments Yet!!!</p>
            {% endif %}
              {% if csubmit %}
              <h2>Your Comment Added successfully</h2>
               {% else %}
               <h2>You can Submit your comment it is valueable for us!!</h2>
                 {% if messages %}
                 {% for message in messages %}

               <div class="alert alert-{{message.tags }}">
                {{message}}
                 </div>

                 {% endfor %}
              {% endif %}
                 <form method="post">
                   {{form.as_p}}
                   {% csrf_token %}
                   <input type="submit" name="" value="Submit Comment" class="btn btn-primary">
                 </form>
				
              {% endif %}
			  {% if request.user.is_authenticated %}

			  <a class="dropdown-item btn btn-outline-info  btn-sm" href="/accounts/logout"><font size="2">Logout</font></a>
			  {% else %}
						<div class="soci">
							<ul>
								<li class="hvr-rectangle-out"> Please Login with  </li>
								<li class="hvr-rectangle-out"><a class="fb" href="{% provider_login_url "facebook" method="js_sdk" %}"></a></li>
								<li class="hvr-rectangle-out"><a class="twit" href="{% provider_login_url "twitter" method="js_sdk" %}"></a></li>
								<li class="hvr-rectangle-out"><a class="goog" href="{% provider_login_url "google" method="js_sdk" %}"></a></li>
								
							</ul>
						</div>
				{% endif %}		
						<div class="clearfix"></div>
			</div> 
			<div class="clearfix"></div>
			
			</div>
		</div>
		<!-- technology-right -->
		<div class="col-md-3 technology-right">
				
				
				<div class="blo-top1">
							
					<div class="tech-btm">
					<div class="search-1 wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
							<form action="#" method="post">
								<input type="search" name="Search" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}" required="">
								<input type="submit" value=" ">
							</form>
						</div>
					<h4>Popular Posts </h4>
                    {% for item in popular_post%}
						<div class="blog-grids wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
							<div class="blog-grid-left">
                            
								<a href="singlepage.html"><img src={{ item.image.url }} class="img-responsive" alt="" width="100px" height="76px"></a>
							</div>
							<div class="blog-grid-right">
								
								<h5><a href="{% url 'defence:post_detail'  pk=item.id %}">{{item.title|truncatechars:25}}</a> 
                                <br> views: {{item.post_views}} </h5>
							</div>
							<div class="clearfix"> </div>
						</div>
                        {% endfor %}
						
						<div class="insta wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
					
					</div>
					
					
					</div>
					
					
					
				</div>
				
			
		</div>
		<div class="clearfix"></div>
	</div>
</div>


</body>
</html>
{% endblock %}